schema: spec-driven

context: |
  Tech stack: Go, C#, Java
  We use conventional commits
  Domain: PIX payment system in Brazil
  Tests: Unit tests, Integration tests, Performance tests
  Tests stacks: Go - Testify, C# - xUnit, Java - JUnit, Robot Framework for integration tests, K6 for performance tests

rules:
  - Use clear and descriptive commit messages following the conventional commits format.
  - Ensure all code changes are accompanied by relevant tests.
  - Maintain a consistent code style across all languages used in the project.
  - Document any significant architectural decisions in the project's documentation.
  - Local environment uses Docker and Docker Compose for development and testing.
  - Monorepo Build and Tests are automated using NX for Go, C#, and Java projects.
  - Makefile is used to streamline common tasks such as building, testing, and deploying the application on local environments.
